### ISSUE TITLE
I'm still in this group, for some reason :o

### ISSUE THREAD

**Issue by marcohamersma** [edenspiekermann/espi-devblog#15]
Hey Folks,
For some reason — even though I'm not in the org — I still get mentions for espi/js, and espi/devs 😊. Any idea why this might still be happening?

**Comment by nburkley** [comment]
Hey @marcohamersma. It's probably because for some public repos, like this one, and you're "watching" them. https://github.com/edenspiekermann/espi-devblog/watchers. 

It *shouldn't* be tied to `espi/js` or `espi/devs` as you're not in any edenspiekermann groups any more.

**Comment by marcohamersma** [comment]
Ah right, that's it, hehe.

Cheers
