### ISSUE TITLE
Additional content for the MJML post

### ISSUE THREAD

**Issue by zfhui** [edenspiekermann/espi-devblog#20]
While setting mjml up for the MyWings page I came across the case where we are using a general email layout (in `app/views/layouts/mailer.html.erb`), which is included then in all the emails. 

Since this is the standard setup in a rails app, I thought that adding [the solution](https://github.com/sighmon/mjml-rails/issues/4) about how to do this would complete Hugo's blog post. 

@HugoGiraudel: what do you think?

**Comment by HugoGiraudel** [comment]
Sounds good. :)
