### ISSUE TITLE
Code font is not right

### ISSUE THREAD

**Issue by HugoGiraudel** [edenspiekermann/espi-devblog#23]
It appears to be serif. I guess `Lucida console` is not a system font. In any case, there should always be a font family fallback. ;)

<img width="675" alt="screen shot 2017-01-16 at 6 10 46 pm" src="https://cloud.githubusercontent.com/assets/1889710/21992552/2f12de5e-dc17-11e6-93f3-9049fc0eb57d.png">

**Comment by livmadsen** [comment]
Thanks :)

This was Fira before, I think. But in any case, I'd prefer to add a solution for code blocks to our main site styles, so we can also comfortably add code to our Magazine posts, and then use those in the dev-blog as well.

Related issue on main repo: https://github.com/edenspiekermann/espi-website-v5/issues/202.

**Comment by eschaefer** [comment]
@livmadsen Related: http://dev.edenspiekermann.com/2016/03/07/introducing-a11y-toggle/

<img width="646" alt="screen shot 2017-01-20 at 21 55 43" src="https://cloud.githubusercontent.com/assets/547148/22165265/3e0a06ac-df5b-11e6-8469-47587518eff9.png">

**Comment by livmadsen** [comment]
@eschaefer Which browser?
Niall sees the same as you, but I see this very neat looking thing:
<img width="687" alt="screenshot 2017-01-23 10 47 29" src="https://cloud.githubusercontent.com/assets/1394553/22199069/a66175e6-e159-11e6-8578-a1c7858e1b0c.png">

**Comment by nburkley** [comment]
Chrome, Firefox, Safari, Opera....

**Comment by eschaefer** [comment]
Yeah, was Chrome 55 for me.

**Comment by livmadsen** [comment]
@eschaefer Niall and I had a look together, turns out it was a difference in scrollbar settings.
We now only have overflow-x scrolling on pre-blocks.

**Comment by livmadsen** [comment]
As to the original issue: we've gone back to prioritising Fira. And fallback is now a full stack for Lucida console (http://www.cssfontstack.com/lucida-console).
