### ISSUE TITLE
Some typo in article "Rails Multitenant Site"

### ISSUE THREAD

**Issue by zfhui** [edenspiekermann/espi-devblog#24]
A visitor of our blog raised the following typos in @nburkley's article [Creating a multi-tenant site with rails](http://dev.edenspiekermann.com/2016/09/09/rails-multitenant-site/): 
![image1](https://cloud.githubusercontent.com/assets/2130051/22692862/27323b5e-ed41-11e6-8b21-62d428ded407.JPG)
![image2](https://cloud.githubusercontent.com/assets/2130051/22692863/2732ef7c-ed41-11e6-8094-bfc782f1f2b0.JPG)

**Comment by nburkley** [comment]
Thanks @HugoGiraudel and @zfhui
