### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by eschaefer** [edenspiekermann/espi-devblog#4]
Would be nice to just see where links come in from. 

- [ ] Add Google Analytics tracking code.

**Comment by mattcav** [comment]
Do we have an espi google account?

**Comment by eschaefer** [comment]
Ah yeah, found the login info :)

**Comment by eschaefer** [comment]
@artibella @nburkley Can one of you generate an Analytics ID and share it here? I no longer can access that account.

**Comment by eschaefer** [comment]
@artibella @nburkley meow? ☝️

**Comment by nburkley** [comment]
@eschaefer I don't have access to this I'm afraid 😿

**Comment by eschaefer** [comment]
@livmadsen + @martzoukos is this something one of y'all can do?

**Comment by livmadsen** [comment]
Sorry, @eschaefer, I don't seem to have access either :/

**Comment by livmadsen** [comment]
Oh… the web-team credentials are in 1Pass. Maybe from there :)

**Comment by nburkley** [comment]
@livmadsen Nope, I checked a while ago. We can view the analytics with that account but not create new properties.

**Comment by eschaefer** [comment]
@livmadsen yeah, I've got the credentials but Google's 2FA hates that I'm in the US and wants to send me a text. I don't have the original phone # that account was created with :(
